services:
  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=pawitkowski@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  judge:
    build: frontend
    environment:
      - PISTON_URL=http://piston:2000
      - NEXTAUTH_URL=http://judge.witek.ovh
      - NEXTAUTH_SECRET=vuqhdwXviFR5Tp8Cvr7OVa/eCAkx25C/CSJRuDVmjsY=
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.judge.rule=Host(`judge.witek.ovh`)"
      - "traefik.http.routers.judge.entrypoints=websecure"
      - "traefik.http.routers.judge.tls.certresolver=myresolver"

  piston:
    image: ghcr.io/engineer-man/piston
    restart: always
    volumes:
        - ./piston/packages:/piston/packages
    tmpfs:
        - /piston/jobs:exec,uid=1000,gid=1000,mode=711
        - /tmp:exec
    environment:
    #    - PISTON_DISABLE_NETWORKING=true
        - PISTON_LOG_LEVEL=DEBUG

        